# Generated by Django 4.1.4 on 2023-01-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
