# Generated by Django 4.1.4 on 2023-01-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
