# Generated by Django 4.1.5 on 2023-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_signin_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coin', models.CharField(max_length=10, verbose_name='NameCoin')),
            ],
        ),
    ]
