# Generated by Django 4.1.5 on 2023-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_coin', models.CharField(max_length=10, verbose_name='NameCoin')),
                ('choice_status', models.CharField(max_length=15, verbose_name='Select')),
            ],
        ),
        migrations.DeleteModel(
            name='NameCoin',
        ),
    ]
