# Generated by Django 4.2 on 2023-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_searchcoinmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchCoinModel',
        ),
    ]
